name: Optimize Images

on:
  push:
    paths:
      - 'Pictures/**'
  workflow_dispatch:

jobs:
  compress-images:
    if: ${{ !contains(github.event.head_commit.message, 'Auto optimize images') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WebP
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Optimize images
        run: |
          find Pictures -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | while read file; do
            echo "Processing $file"

            if [[ "$file" == *.webp ]]; then
              mv "$file" "${file}.bak"
              cwebp -q 85 "${file}.bak" -o "$file"
              rm "${file}.bak"
            else
              cwebp -resize 1400 800 -q 85 "$file" -o "${file%.*}.webp"
              rm "$file"
            fi
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Pictures
          git diff --cached --quiet || git commit -m "Auto optimize images"
          git push
